### ISSUE TITLE
Content API shows in header

### ISSUE THREAD

**Issue by thimiraonline** [hasalaonline/Techie-Orbit-Blog-Template#1]
I think you have implement the Ghost CMS content API call in client side. Try server side rendering. Otherwise the content API is expose to public and anyone can build a website with connecting to your content API.

If you are going to implement the SSR then you have to rebuilt the website when you publish a new post and edit an existing post. You can trigger rebuilt with using webhooks. 

<img width="751" alt="Screenshot 2024-08-04 at 9 19 13 PM" src="https://github.com/user-attachments/assets/f6bc3adb-f3e5-4873-a7e2-e46a3eb3792a">

**Comment by hasalaonline** [comment]
Thanks for pointing that out! 🙌 I’ve implemented server-side rendering (SSR) for the Next.js route to address the issue and hide the actual API call from the client. This approach ensures that the Ghost CMS content API remains secure and prevents unauthorized access to the content.🔒
