### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by thimiraonline** [hasalaonline/Techie-Orbit-Blog-Template#2]
I just go through the demo website and navigated to the last page through the pagination and it shows nothing. When the las post is in the current page, disable or hide the next button in pagination. other wise users will see empty page without posts. 

And make sure to show the featured post only in the first page.

<img width="1430" alt="Screenshot 2024-08-04 at 9 28 14 PM" src="https://github.com/user-attachments/assets/389afa82-5cae-4bf6-8bb8-2f9631a9230d">

**Comment by hasalaonline** [comment]
I’ve reviewed the pagination and post display for the demo website. Here are the updates I’ve made:

1. Pagination Adjustment:

 - The "Next" button on the pagination will now be hidden if the last post is on the current page. This prevents users from navigating to an empty page when they’re already on the last page.

2. Featured Post Display:

- The featured posts will now remain visible as a carousel when navigating to subsequent pages. This ensures that featured content gets highlighted while users can continue to browse other posts.

 If you have any further suggestions or need additional modifications, please let me know!
